options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/restock-rover', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/restock-rover']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'restock-rover', '--image', 'gcr.io/$PROJECT_ID/restock-rover', '--platform', 'managed', '--region', 'us-central1']
